# Introduction to Vectors and Matrices

In [1]:
import numpy as np
x= np.array([[1,0,4],[3,3,1]])
y= np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

# Basics of NumPy Array Object

In [2]:
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print("We just create a ", type(x))

We just create a  <class 'numpy.ndarray'>


In [4]:
print("Our template has shape as" ,x.shape)

Our template has shape as (2, 3)


In [5]:
print("Total size is",x.size)

Total size is 6


In [6]:
print("The dimension of our array is " ,x.ndim)

The dimension of our array is  2


In [7]:
print("Data type of elements are",x.dtype)

Data type of elements are int32


In [8]:
print("It consumes",x.nbytes,"bytes")

It consumes 24 bytes


In [11]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.float)
print(x)
print(x.nbytes)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
48


In [12]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.complex)
print(x)
print(x.nbytes)

[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j]]
96


In [13]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[         1          2          3]
 [         4 4294967291          6]]
24


In [14]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 comsues",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 comsues",x.nbytes, "bytes")

int64 comsues 48 bytes
int32 comsues 24 bytes


In [15]:
x_copy = np.array(x, dtype = np.float)
x_copy 

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [16]:
x_copy_int = x_copy.astype(np.int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x_copy

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [18]:
Data_Cancer= np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(Data_Cancer_New.nbytes)

<class 'numpy.ndarray'>
float64
80000000
40000000


# NumPy Array Operations

In [20]:
my_list = [2, 14, 6, 8, 4, 16, 10, 9]
my_array =np.asarray(my_list)
type(my_array)

numpy.ndarray

In [21]:
my_array +2

array([ 4, 16,  8, 10,  6, 18, 12, 11])

In [22]:
my_array -1

array([ 1, 13,  5,  7,  3, 15,  9,  8])

In [23]:
my_array *2

array([ 4, 28, 12, 16,  8, 32, 20, 18])

In [24]:
my_array /2

array([ 1. ,  7. ,  3. ,  4. ,  2. ,  8. ,  5. ,  4.5])

In [25]:
second_array = np.zeros(8) + 3
second_array 

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [26]:
my_array - second_array 

array([ -1.,  11.,   3.,   5.,   1.,  13.,   7.,   6.])

In [27]:
second_array / my_array 

array([ 1.5       ,  0.21428571,  0.5       ,  0.375     ,  0.75      ,
        0.1875    ,  0.3       ,  0.33333333])

In [28]:
second_array = np.ones(8)+3
second_array

array([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.])

In [29]:
my_array - second_array 

array([ -2.,  10.,   2.,   4.,   0.,  12.,   6.,   5.])

In [30]:
second_array / my_array 

array([ 2.        ,  0.28571429,  0.66666667,  0.5       ,  1.        ,
        0.25      ,  0.4       ,  0.44444444])

In [31]:
second_array = np.identity(8)
second_array

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [32]:
second_array = np.identity(8)+3
second_array

array([[ 4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  4.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  4.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  4.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  4.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  4.]])

In [33]:
my_array - second_array 

array([[ -2.,  11.,   3.,   5.,   1.,  13.,   7.,   6.],
       [ -1.,  10.,   3.,   5.,   1.,  13.,   7.,   6.],
       [ -1.,  11.,   2.,   5.,   1.,  13.,   7.,   6.],
       [ -1.,  11.,   3.,   4.,   1.,  13.,   7.,   6.],
       [ -1.,  11.,   3.,   5.,   0.,  13.,   7.,   6.],
       [ -1.,  11.,   3.,   5.,   1.,  12.,   7.,   6.],
       [ -1.,  11.,   3.,   5.,   1.,  13.,   6.,   6.],
       [ -1.,  11.,   3.,   5.,   1.,  13.,   7.,   5.]])

In [34]:
second_array / my_array 

array([[ 2.        ,  0.21428571,  0.5       ,  0.375     ,  0.75      ,
         0.1875    ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.28571429,  0.5       ,  0.375     ,  0.75      ,
         0.1875    ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.66666667,  0.375     ,  0.75      ,
         0.1875    ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.5       ,  0.5       ,  0.75      ,
         0.1875    ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.5       ,  0.375     ,  1.        ,
         0.1875    ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.5       ,  0.375     ,  0.75      ,
         0.25      ,  0.3       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.5       ,  0.375     ,  0.75      ,
         0.1875    ,  0.4       ,  0.33333333],
       [ 1.5       ,  0.21428571,  0.5       ,  0.375     ,  0.75      ,
         0.1875    ,  0.3       ,  0.44444444]])

In [35]:
x = np.arange(3,7,0.5)
x

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5])

In [36]:
x = np.linspace(1.2, 40.5, num=65)
x

array([  1.2      ,   1.8140625,   2.428125 ,   3.0421875,   3.65625  ,
         4.2703125,   4.884375 ,   5.4984375,   6.1125   ,   6.7265625,
         7.340625 ,   7.9546875,   8.56875  ,   9.1828125,   9.796875 ,
        10.4109375,  11.025    ,  11.6390625,  12.253125 ,  12.8671875,
        13.48125  ,  14.0953125,  14.709375 ,  15.3234375,  15.9375   ,
        16.5515625,  17.165625 ,  17.7796875,  18.39375  ,  19.0078125,
        19.621875 ,  20.2359375,  20.85     ,  21.4640625,  22.078125 ,
        22.6921875,  23.30625  ,  23.9203125,  24.534375 ,  25.1484375,
        25.7625   ,  26.3765625,  26.990625 ,  27.6046875,  28.21875  ,
        28.8328125,  29.446875 ,  30.0609375,  30.675    ,  31.2890625,
        31.903125 ,  32.5171875,  33.13125  ,  33.7453125,  34.359375 ,
        34.9734375,  35.5875   ,  36.2015625,  36.815625 ,  37.4296875,
        38.04375  ,  38.6578125,  39.271875 ,  39.8859375,  40.5      ])

In [37]:
np.geomspace(1, 625, num=5)

array([   1.,    5.,   25.,  125.,  625.])

In [38]:
np.logspace(3, 4, num=5)

array([  1000.        ,   1778.27941004,   3162.27766017,   5623.4132519 ,
        10000.        ])

In [39]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

array([ 3.        ,  3.2237098 ,  3.46410162,  3.72241944,  4.        ])

In [40]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

array([ True, False, False,  True], dtype=bool)

In [41]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

False

In [42]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

array([False,  True,  True, False], dtype=bool)

In [43]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

array([ True,  True, False,  True], dtype=bool)

In [44]:
np.logical_and(x,y)

array([False,  True, False, False], dtype=bool)

In [45]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True], dtype=bool)

In [46]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [47]:
np.log(x)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [48]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [52]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [54]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
np.sum(x)

36

In [56]:
np.amin(x)

0

In [57]:
np.amax(x)

8

In [58]:
np.amin(x, axis=0)

array([0, 1, 2])

In [59]:
np.amin(x, axis=1)

array([0, 3, 6])

In [60]:
np.percentile(x, 80)

6.4000000000000004

In [61]:
x = np.array([1,-21,3,-3])
np.argmax(x)

2

In [62]:
np.argmin(x)

1

In [63]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [64]:
np.mean(x)

7.666666666666667

In [65]:
np.mean(x, axis=0)

array([ 11. ,   7.5,   4.5])

In [66]:
np.mean(x, axis=1)

array([  3.33333333,  12.        ])

In [67]:
np.median(x)

4.5

In [68]:
np.std(x)

6.3944420310836261

# Working with Multidimensional Arrays

In [69]:
c = np.ones((4, 4))
c*c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [70]:
c.dot(c)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [71]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [72]:
y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y,x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [78]:
from scipy import stats
x= np.random.rand(100,10)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

array([[  5.46011575e-01,   8.30007104e-02,  -9.72899085e-02,
         -1.17492785e+00,   4.07031246e-04,   9.85652100e-01],
       [  4.79292653e-01,   8.13883169e-02,   1.00411352e-01,
         -1.15988275e+00,   1.27241020e-02,   9.85985488e-01],
       [  4.81319367e-01,   8.34107619e-02,   5.55926602e-02,
         -1.20006450e+00,   7.49534810e-03,   9.86671083e-01],
       [  5.26977277e-01,   9.33829059e-02,  -1.12640661e-01,
         -1.19955646e+00,   5.74237697e-03,   9.94980830e-01],
       [  5.42622228e-01,   8.92615897e-02,  -1.79102183e-01,
         -1.13744108e+00,   2.27821933e-03,   9.93861532e-01],
       [  4.84397369e-01,   9.18274523e-02,   2.33663872e-01,
         -1.36827574e+00,   1.18986562e-02,   9.96563489e-01],
       [  4.41436165e-01,   9.54357485e-02,   3.48194314e-01,
         -1.15588500e+00,   1.77608372e-03,   9.93865324e-01],
       [  5.34834409e-01,   7.61735119e-02,  -2.10467450e-01,
         -1.01442389e+00,   2.44706226e-02,   9.97784091e-01],


In [79]:
import numpy.ma as ma
x = np.arange(6)
x.mean()
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

3.0

In [80]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

array([[ nan,  nan,  nan,  nan,  nan],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [81]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

array([[ 12.5,  13.5,  14.5,  15.5,  16.5],
       [  5. ,   6. ,   7. ,   8. ,   9. ],
       [ 10. ,  11. ,  12. ,  13. ,  14. ],
       [ 15. ,  16. ,  17. ,  18. ,  19. ],
       [ 20. ,  21. ,  22. ,  23. ,  24. ]])

# Indexing, Slicing, Reshaping, Resizing, Broadcasting

In [82]:
x =["USA","France", "Germany","England"]
x[2]

'Germany'

In [83]:
x =('USA',3,"France",4)
x[2]

'France'

In [85]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x[5]

5

In [87]:
x[-2]

8

In [88]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [89]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x[2:8:2]

array([2, 4, 6])

In [91]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [94]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [95]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
x[[0,1,3],[0,1,3]]

array([ 0,  5, 15])

In [99]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
np.resize(x,(2,2))

array([[0, 1],
       [2, 3]])

In [101]:
np.resize(x,(6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [102]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [103]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.]])

In [104]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [105]:
y = np.arange(2).reshape(1,2)
y

array([[0, 1]])

In [106]:
x*y

array([[0, 1],
       [0, 3]])